/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FinixIndexRouteImport } from './routes/finix.index'
import { Route as FinixSlugRouteImport } from './routes/finix.$slug'
import { Route as FinixCertificationRouteImport } from './routes/finix.certification'
import { Route as FinixKpiRouteImport } from './routes/finix.kpi'
import { Route as FinixSurveyRouteImport } from './routes/finix.survey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixIndexRoute = FinixIndexRouteImport.update({
  id: '/finix/',
  path: '/finix/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixSlugRoute = FinixSlugRouteImport.update({
  id: '/finix/$slug',
  path: '/finix/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixCertificationRoute = FinixCertificationRouteImport.update({
  id: '/finix/certification',
  path: '/finix/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixKpiRoute = FinixKpiRouteImport.update({
  id: '/finix/kpi',
  path: '/finix/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixSurveyRoute = FinixSurveyRouteImport.update({
  id: '/finix/survey',
  path: '/finix/survey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finix/$slug': typeof FinixSlugRoute
  '/finix/certification': typeof FinixCertificationRoute
  '/finix/kpi': typeof FinixKpiRoute
  '/finix/survey': typeof FinixSurveyRoute
  '/finix/': typeof FinixIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finix/$slug': typeof FinixSlugRoute
  '/finix/certification': typeof FinixCertificationRoute
  '/finix/kpi': typeof FinixKpiRoute
  '/finix/survey': typeof FinixSurveyRoute
  '/finix': typeof FinixIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finix/$slug': typeof FinixSlugRoute
  '/finix/certification': typeof FinixCertificationRoute
  '/finix/kpi': typeof FinixKpiRoute
  '/finix/survey': typeof FinixSurveyRoute
  '/finix/': typeof FinixIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/finix/$slug'
    | '/finix/certification'
    | '/finix/kpi'
    | '/finix/survey'
    | '/finix/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/finix/$slug'
    | '/finix/certification'
    | '/finix/kpi'
    | '/finix/survey'
    | '/finix'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/finix/$slug'
    | '/finix/certification'
    | '/finix/kpi'
    | '/finix/survey'
    | '/finix/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FinixSlugRoute: typeof FinixSlugRoute
  FinixCertificationRoute: typeof FinixCertificationRoute
  FinixKpiRoute: typeof FinixKpiRoute
  FinixSurveyRoute: typeof FinixSurveyRoute
  FinixIndexRoute: typeof FinixIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/': {
      id: '/finix/'
      path: '/finix'
      fullPath: '/finix/'
      preLoaderRoute: typeof FinixIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/$slug': {
      id: '/finix/$slug'
      path: '/finix/$slug'
      fullPath: '/finix/$slug'
      preLoaderRoute: typeof FinixSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/certification': {
      id: '/finix/certification'
      path: '/finix/certification'
      fullPath: '/finix/certification'
      preLoaderRoute: typeof FinixCertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/kpi': {
      id: '/finix/kpi'
      path: '/finix/kpi'
      fullPath: '/finix/kpi'
      preLoaderRoute: typeof FinixKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/survey': {
      id: '/finix/survey'
      path: '/finix/survey'
      fullPath: '/finix/survey'
      preLoaderRoute: typeof FinixSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FinixSlugRoute: FinixSlugRoute,
  FinixCertificationRoute: FinixCertificationRoute,
  FinixKpiRoute: FinixKpiRoute,
  FinixSurveyRoute: FinixSurveyRoute,
  FinixIndexRoute: FinixIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
