/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminPanelRouteImport } from './routes/dashboard/admin-panel'
import { Route as DashboardCertificationsRouteImport } from './routes/dashboard/certifications'
import { Route as DashboardFieldSurveyRouteImport } from './routes/dashboard/field-survey'
import { Route as DashboardKpiEvaluatorRouteImport } from './routes/dashboard/kpi-evaluator'
import { Route as DashboardMyCoursesRouteImport } from './routes/dashboard/my-courses'
import { Route as FinixIndexRouteImport } from './routes/finix.index'
import { Route as FinixSlugRouteImport } from './routes/finix.$slug'
import { Route as FinixCertificationRouteImport } from './routes/finix.certification'
import { Route as FinixKpiRouteImport } from './routes/finix.kpi'
import { Route as FinixSurveyRouteImport } from './routes/finix.survey'
import { Route as DashboardAuthoringIndexRouteImport } from './routes/dashboard/authoring/index'
import { Route as DashboardAuthoringModuleIdRouteImport } from './routes/dashboard/authoring/$moduleId'
import { Route as DashboardModuleSlugRouteImport } from './routes/dashboard/module.$slug'
import { Route as DashboardQuizSlugTierRouteImport } from './routes/dashboard/quiz.$slug.$tier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPanelRoute = DashboardAdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificationsRoute = DashboardCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFieldSurveyRoute = DashboardFieldSurveyRouteImport.update({
  id: '/field-survey',
  path: '/field-survey',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKpiEvaluatorRoute = DashboardKpiEvaluatorRouteImport.update({
  id: '/kpi-evaluator',
  path: '/kpi-evaluator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyCoursesRoute = DashboardMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => DashboardRoute,
} as any)
const FinixIndexRoute = FinixIndexRouteImport.update({
  id: '/finix/',
  path: '/finix/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixSlugRoute = FinixSlugRouteImport.update({
  id: '/finix/$slug',
  path: '/finix/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixCertificationRoute = FinixCertificationRouteImport.update({
  id: '/finix/certification',
  path: '/finix/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixKpiRoute = FinixKpiRouteImport.update({
  id: '/finix/kpi',
  path: '/finix/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const FinixSurveyRoute = FinixSurveyRouteImport.update({
  id: '/finix/survey',
  path: '/finix/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthoringIndexRoute = DashboardAuthoringIndexRouteImport.update({
  id: '/authoring/',
  path: '/authoring/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthoringModuleIdRoute =
  DashboardAuthoringModuleIdRouteImport.update({
    id: '/authoring/$moduleId',
    path: '/authoring/$moduleId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardModuleSlugRoute = DashboardModuleSlugRouteImport.update({
  id: '/module/$slug',
  path: '/module/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizSlugTierRoute = DashboardQuizSlugTierRouteImport.update({
  id: '/quiz/$slug/$tier',
  path: '/quiz/$slug/$tier',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin-panel': typeof DashboardAdminPanelRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/field-survey': typeof DashboardFieldSurveyRoute
  '/dashboard/kpi-evaluator': typeof DashboardKpiEvaluatorRoute
  '/dashboard/my-courses': typeof DashboardMyCoursesRoute
  '/finix/$slug': typeof FinixSlugRoute
  '/finix/certification': typeof FinixCertificationRoute
  '/finix/kpi': typeof FinixKpiRoute
  '/finix/survey': typeof FinixSurveyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finix/': typeof FinixIndexRoute
  '/dashboard/authoring/$moduleId': typeof DashboardAuthoringModuleIdRoute
  '/dashboard/module/$slug': typeof DashboardModuleSlugRoute
  '/dashboard/authoring/': typeof DashboardAuthoringIndexRoute
  '/dashboard/quiz/$slug/$tier': typeof DashboardQuizSlugTierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin-panel': typeof DashboardAdminPanelRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/field-survey': typeof DashboardFieldSurveyRoute
  '/dashboard/kpi-evaluator': typeof DashboardKpiEvaluatorRoute
  '/dashboard/my-courses': typeof DashboardMyCoursesRoute
  '/finix/$slug': typeof FinixSlugRoute
  '/finix/certification': typeof FinixCertificationRoute
  '/finix/kpi': typeof FinixKpiRoute
  '/finix/survey': typeof FinixSurveyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finix': typeof FinixIndexRoute
  '/dashboard/authoring/$moduleId': typeof DashboardAuthoringModuleIdRoute
  '/dashboard/module/$slug': typeof DashboardModuleSlugRoute
  '/dashboard/authoring': typeof DashboardAuthoringIndexRoute
  '/dashboard/quiz/$slug/$tier': typeof DashboardQuizSlugTierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin-panel': typeof DashboardAdminPanelRoute
  '/dashboard/certifications': typeof DashboardCertificationsRoute
  '/dashboard/field-survey': typeof DashboardFieldSurveyRoute
  '/dashboard/kpi-evaluator': typeof DashboardKpiEvaluatorRoute
  '/dashboard/my-courses': typeof DashboardMyCoursesRoute
  '/finix/$slug': typeof FinixSlugRoute
  '/finix/certification': typeof FinixCertificationRoute
  '/finix/kpi': typeof FinixKpiRoute
  '/finix/survey': typeof FinixSurveyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finix/': typeof FinixIndexRoute
  '/dashboard/authoring/$moduleId': typeof DashboardAuthoringModuleIdRoute
  '/dashboard/module/$slug': typeof DashboardModuleSlugRoute
  '/dashboard/authoring/': typeof DashboardAuthoringIndexRoute
  '/dashboard/quiz/$slug/$tier': typeof DashboardQuizSlugTierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin-panel'
    | '/dashboard/certifications'
    | '/dashboard/field-survey'
    | '/dashboard/kpi-evaluator'
    | '/dashboard/my-courses'
    | '/finix/$slug'
    | '/finix/certification'
    | '/finix/kpi'
    | '/finix/survey'
    | '/dashboard/'
    | '/finix/'
    | '/dashboard/authoring/$moduleId'
    | '/dashboard/module/$slug'
    | '/dashboard/authoring/'
    | '/dashboard/quiz/$slug/$tier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/admin-panel'
    | '/dashboard/certifications'
    | '/dashboard/field-survey'
    | '/dashboard/kpi-evaluator'
    | '/dashboard/my-courses'
    | '/finix/$slug'
    | '/finix/certification'
    | '/finix/kpi'
    | '/finix/survey'
    | '/dashboard'
    | '/finix'
    | '/dashboard/authoring/$moduleId'
    | '/dashboard/module/$slug'
    | '/dashboard/authoring'
    | '/dashboard/quiz/$slug/$tier'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin-panel'
    | '/dashboard/certifications'
    | '/dashboard/field-survey'
    | '/dashboard/kpi-evaluator'
    | '/dashboard/my-courses'
    | '/finix/$slug'
    | '/finix/certification'
    | '/finix/kpi'
    | '/finix/survey'
    | '/dashboard/'
    | '/finix/'
    | '/dashboard/authoring/$moduleId'
    | '/dashboard/module/$slug'
    | '/dashboard/authoring/'
    | '/dashboard/quiz/$slug/$tier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FinixSlugRoute: typeof FinixSlugRoute
  FinixCertificationRoute: typeof FinixCertificationRoute
  FinixKpiRoute: typeof FinixKpiRoute
  FinixSurveyRoute: typeof FinixSurveyRoute
  FinixIndexRoute: typeof FinixIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-panel': {
      id: '/dashboard/admin-panel'
      path: '/admin-panel'
      fullPath: '/dashboard/admin-panel'
      preLoaderRoute: typeof DashboardAdminPanelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certifications': {
      id: '/dashboard/certifications'
      path: '/certifications'
      fullPath: '/dashboard/certifications'
      preLoaderRoute: typeof DashboardCertificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/field-survey': {
      id: '/dashboard/field-survey'
      path: '/field-survey'
      fullPath: '/dashboard/field-survey'
      preLoaderRoute: typeof DashboardFieldSurveyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kpi-evaluator': {
      id: '/dashboard/kpi-evaluator'
      path: '/kpi-evaluator'
      fullPath: '/dashboard/kpi-evaluator'
      preLoaderRoute: typeof DashboardKpiEvaluatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-courses': {
      id: '/dashboard/my-courses'
      path: '/my-courses'
      fullPath: '/dashboard/my-courses'
      preLoaderRoute: typeof DashboardMyCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/finix/': {
      id: '/finix/'
      path: '/finix'
      fullPath: '/finix/'
      preLoaderRoute: typeof FinixIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/$slug': {
      id: '/finix/$slug'
      path: '/finix/$slug'
      fullPath: '/finix/$slug'
      preLoaderRoute: typeof FinixSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/certification': {
      id: '/finix/certification'
      path: '/finix/certification'
      fullPath: '/finix/certification'
      preLoaderRoute: typeof FinixCertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/kpi': {
      id: '/finix/kpi'
      path: '/finix/kpi'
      fullPath: '/finix/kpi'
      preLoaderRoute: typeof FinixKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finix/survey': {
      id: '/finix/survey'
      path: '/finix/survey'
      fullPath: '/finix/survey'
      preLoaderRoute: typeof FinixSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/authoring/': {
      id: '/dashboard/authoring/'
      path: '/authoring'
      fullPath: '/dashboard/authoring/'
      preLoaderRoute: typeof DashboardAuthoringIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/authoring/$moduleId': {
      id: '/dashboard/authoring/$moduleId'
      path: '/authoring/$moduleId'
      fullPath: '/dashboard/authoring/$moduleId'
      preLoaderRoute: typeof DashboardAuthoringModuleIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/module/$slug': {
      id: '/dashboard/module/$slug'
      path: '/module/$slug'
      fullPath: '/dashboard/module/$slug'
      preLoaderRoute: typeof DashboardModuleSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz/$slug/$tier': {
      id: '/dashboard/quiz/$slug/$tier'
      path: '/quiz/$slug/$tier'
      fullPath: '/dashboard/quiz/$slug/$tier'
      preLoaderRoute: typeof DashboardQuizSlugTierRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminPanelRoute: typeof DashboardAdminPanelRoute
  DashboardCertificationsRoute: typeof DashboardCertificationsRoute
  DashboardFieldSurveyRoute: typeof DashboardFieldSurveyRoute
  DashboardKpiEvaluatorRoute: typeof DashboardKpiEvaluatorRoute
  DashboardMyCoursesRoute: typeof DashboardMyCoursesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAuthoringModuleIdRoute: typeof DashboardAuthoringModuleIdRoute
  DashboardModuleSlugRoute: typeof DashboardModuleSlugRoute
  DashboardAuthoringIndexRoute: typeof DashboardAuthoringIndexRoute
  DashboardQuizSlugTierRoute: typeof DashboardQuizSlugTierRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminPanelRoute: DashboardAdminPanelRoute,
  DashboardCertificationsRoute: DashboardCertificationsRoute,
  DashboardFieldSurveyRoute: DashboardFieldSurveyRoute,
  DashboardKpiEvaluatorRoute: DashboardKpiEvaluatorRoute,
  DashboardMyCoursesRoute: DashboardMyCoursesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAuthoringModuleIdRoute: DashboardAuthoringModuleIdRoute,
  DashboardModuleSlugRoute: DashboardModuleSlugRoute,
  DashboardAuthoringIndexRoute: DashboardAuthoringIndexRoute,
  DashboardQuizSlugTierRoute: DashboardQuizSlugTierRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FinixSlugRoute: FinixSlugRoute,
  FinixCertificationRoute: FinixCertificationRoute,
  FinixKpiRoute: FinixKpiRoute,
  FinixSurveyRoute: FinixSurveyRoute,
  FinixIndexRoute: FinixIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
