-- Module 6: Mesh Security & Network Hardening (original writing)

INSERT INTO public.modules (slug, code, track_id, title, title_ar, summary, summary_ar, external_url, position) VALUES ('sonoff-mesh-security-hardening', 'M16', 'sonoff-installer-certification', 'Mesh Security & Network Hardening', 'أمن الشبكة الشبكية وتحصين الشبكة', 'Network segmentation for IoT devices, credential hygiene and shared access, and a safe firmware update policy for live installations.', 'تجزئة الشبكة لأجهزة إنترنت الأشياء، نظافة بيانات الاعتماد والوصول المشترك، وسياسة تحديث آمنة للبرامج الثابتة في التركيبات المباشرة.', NULL, 16);
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'Network Segmentation for Smart Home Devices', 'تجزئة الشبكة لأجهزة المنزل الذكي', 'Placing IoT devices on a separate VLAN or guest network from the household''s primary computers and phones limits the blast radius if any single device is ever compromised. Installers should configure the gateway/router to isolate device traffic where the hardware supports it, while still allowing the specific ports and local discovery protocols each ecosystem needs (mDNS for HomeKit, SSDP for some hubs). Documenting which VLAN each device lives on is part of a professional handover package.', 'وضع أجهزة إنترنت الأشياء على شبكة VLAN أو شبكة ضيوف منفصلة عن أجهزة الكمبيوتر والهواتف الأساسية للأسرة يحد من نطاق الضرر إذا تم اختراق أي جهاز. يجب على الفني إعداد البوابة/الموجه لعزل حركة مرور الأجهزة حيثما يدعم العتاد ذلك، مع السماح بالمنافذ وبروتوكولات الاكتشاف المحلية التي تحتاجها كل منظومة (mDNS لـ HomeKit، SSDP لبعض البوابات). توثيق شبكة VLAN التي يقيم عليها كل جهاز جزء من حزمة التسليم الاحترافية.', 1 FROM public.modules WHERE slug = 'sonoff-mesh-security-hardening';
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'Credential Hygiene: Passwords, PINs & Shared Access', 'نظافة بيانات الاعتماد: كلمات المرور وأرقام PIN والوصول المشترك', 'Default device PINs and admin passwords should always be changed during commissioning, never left at factory defaults. When handing an account to a customer, use each platform''s built-in device-sharing or family-member roles instead of sharing a single admin login among multiple people — this keeps an audit trail and lets access be revoked individually (e.g. after a tenant moves out) without resetting every device.', 'يجب دائمًا تغيير أرقام PIN الافتراضية وكلمات مرور المسؤول للأجهزة أثناء التشغيل، وعدم تركها على الإعدادات الافتراضية من المصنع. عند تسليم حساب للعميل، استخدم ميزات مشاركة الجهاز أو أدوار أفراد الأسرة المدمجة في كل منصة بدلًا من مشاركة حساب مسؤول واحد بين عدة أشخاص — هذا يحافظ على سجل تدقيق ويتيح إلغاء الوصول فرديًا (مثلًا بعد انتقال مستأجر) دون إعادة ضبط كل جهاز.', 2 FROM public.modules WHERE slug = 'sonoff-mesh-security-hardening';
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'Firmware Update Policy for Deployed Installations', 'سياسة تحديث البرامج الثابتة للتركيبات المنشورة', 'Automatic firmware updates keep devices patched against known vulnerabilities, but pushing updates blindly to a live installation can occasionally break an automation that depended on specific behavior. A balanced policy staggers updates — test on a non-critical device first, then roll out to the rest — and keeps a simple changelog of what was updated and when, so that if something breaks after an update, the cause is easy to trace.', 'تحديثات البرامج الثابتة التلقائية تحافظ على تصحيح الأجهزة ضد الثغرات المعروفة، لكن دفع التحديثات دون تحقق لتركيب مباشر قد يكسر أحيانًا أتمتة كانت تعتمد على سلوك محدد. السياسة المتوازنة توزّع التحديثات — اختبر على جهاز غير حرج أولًا، ثم انشر على البقية — وتحتفظ بسجل تغييرات بسيط لما تم تحديثه ومتى، حتى إذا تعطل شيء بعد تحديث، يسهل تتبع السبب.', 3 FROM public.modules WHERE slug = 'sonoff-mesh-security-hardening';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'bronze', title || ' — Bronze Quiz', title_ar || ' — اختبار برونزي', 80 FROM public.modules WHERE slug = 'sonoff-mesh-security-hardening';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'What is the main benefit of putting smart home devices on a separate VLAN?', 'ما الفائدة الأساسية لوضع أجهزة المنزل الذكي على شبكة VLAN منفصلة؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Limits the impact if a device is ever compromised', 'يحد من الأثر إذا تم اختراق جهاز ما', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze' AND qq.question = 'What is the main benefit of putting smart home devices on a separate VLAN?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Makes devices run faster automatically', 'يجعل الأجهزة أسرع تلقائيًا', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze' AND qq.question = 'What is the main benefit of putting smart home devices on a separate VLAN?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'It removes the need for any password', 'يلغي الحاجة لأي كلمة مرور', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze' AND qq.question = 'What is the main benefit of putting smart home devices on a separate VLAN?';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'Why should firmware updates be staggered rather than pushed to every device at once?', 'لماذا يجب توزيع تحديثات البرامج الثابتة بدلًا من دفعها لكل الأجهزة دفعة واحدة؟', 2 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'To catch any automation-breaking issue on a non-critical device first', 'لاكتشاف أي مشكلة تكسر الأتمتة على جهاز غير حرج أولًا', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze' AND qq.question = 'Why should firmware updates be staggered rather than pushed to every device at once?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Firmware updates always require a hardware replacement', 'التحديثات تتطلب دائمًا استبدال العتاد', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze' AND qq.question = 'Why should firmware updates be staggered rather than pushed to every device at once?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Staggering has no practical benefit', 'لا فائدة عملية للتوزيع', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'bronze' AND qq.question = 'Why should firmware updates be staggered rather than pushed to every device at once?';
