-- Silver & gold tier quizzes for M11-M15 (original writing).

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'silver', title || ' — Silver Quiz', title_ar || ' — اختبار فضي', 85 FROM public.modules WHERE slug = 'sonoff-ecosystem-fundamentals';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A customer''s home has thick concrete interior walls and needs reliable coverage for 15+ devices. What protocol choice minimizes dead zones without a dedicated repeater budget?', 'منزل العميل به جدران خرسانية داخلية سميكة ويحتاج تغطية موثوقة لأكثر من 15 جهازًا. أي اختيار بروتوكول يقلل المناطق الميتة دون ميزانية معيدات مخصصة؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Zigbee, since mains-powered devices act as routers and extend the mesh automatically', 'Zigbee، لأن الأجهزة المتصلة بالكهرباء تعمل كموجّهات وتوسع الشبكة تلقائيًا', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver' AND qq.question = 'A customer''s home has thick concrete interior walls and needs reliable coverage for 15+ devices. What protocol choice minimizes dead zones without a dedicated repeater budget?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Wi-Fi, since it has the longest range of any protocol', 'Wi-Fi، لأن له أطول مدى بين كل البروتوكولات', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver' AND qq.question = 'A customer''s home has thick concrete interior walls and needs reliable coverage for 15+ devices. What protocol choice minimizes dead zones without a dedicated repeater budget?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'It makes no difference which protocol is chosen', 'لا فرق في اختيار البروتوكول', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver' AND qq.question = 'A customer''s home has thick concrete interior walls and needs reliable coverage for 15+ devices. What protocol choice minimizes dead zones without a dedicated repeater budget?';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A customer wants to share limited remote control of their SONOFF devices with a house-sitter for one week only. What''s the professional approach?', 'يريد العميل مشاركة تحكم محدود عن بُعد بأجهزة SONOFF مع جليس منزل لمدة أسبوع واحد فقط. ما النهج الاحترافي؟', 2 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Use eWeLink''s device-sharing feature scoped to specific devices, revocable after the week', 'استخدام ميزة مشاركة الجهاز في eWeLink محصورة بأجهزة محددة، قابلة للإلغاء بعد الأسبوع', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver' AND qq.question = 'A customer wants to share limited remote control of their SONOFF devices with a house-sitter for one week only. What''s the professional approach?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Give the house-sitter the customer''s main account password', 'إعطاء جليس المنزل كلمة مرور حساب العميل الرئيسي', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver' AND qq.question = 'A customer wants to share limited remote control of their SONOFF devices with a house-sitter for one week only. What''s the professional approach?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Factory reset all devices after the house-sitter leaves', 'إعادة ضبط كل الأجهزة للمصنع بعد مغادرة الجليس', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'silver' AND qq.question = 'A customer wants to share limited remote control of their SONOFF devices with a house-sitter for one week only. What''s the professional approach?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'gold', title || ' — Gold Quiz', title_ar || ' — اختبار ذهبي', 85 FROM public.modules WHERE slug = 'sonoff-ecosystem-fundamentals';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'You''re scoping a project with a mix of legacy Wi-Fi-only switches and new Matter-certified devices. What''s the most future-proof integration strategy?', 'تخطط لمشروع يجمع بين مفاتيح Wi-Fi قديمة وأجهزة معتمدة من Matter جديدة. ما استراتيجية الدمج الأكثر مقاومة للمستقبل؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'gold';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Bridge the legacy devices into the same automation platform as the Matter devices so both are controllable from one interface, while planning to phase out Wi-Fi-only units over time', 'ربط الأجهزة القديمة بنفس منصة الأتمتة الخاصة بأجهزة Matter بحيث يمكن التحكم بالجميع من واجهة واحدة، مع التخطيط للتخلص التدريجي من وحدات Wi-Fi فقط', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'gold' AND qq.question = 'You''re scoping a project with a mix of legacy Wi-Fi-only switches and new Matter-certified devices. What''s the most future-proof integration strategy?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Replace all legacy devices immediately regardless of customer budget', 'استبدال جميع الأجهزة القديمة فورًا بغض النظر عن ميزانية العميل', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'gold' AND qq.question = 'You''re scoping a project with a mix of legacy Wi-Fi-only switches and new Matter-certified devices. What''s the most future-proof integration strategy?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Keep the two device groups on completely separate, unconnected systems permanently', 'إبقاء المجموعتين على أنظمة منفصلة تمامًا وغير متصلة بشكل دائم', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-ecosystem-fundamentals' AND q.tier = 'gold' AND qq.question = 'You''re scoping a project with a mix of legacy Wi-Fi-only switches and new Matter-certified devices. What''s the most future-proof integration strategy?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'silver', title || ' — Silver Quiz', title_ar || ' — اختبار فضي', 85 FROM public.modules WHERE slug = 'sonoff-professional-installation';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'During commissioning, a customer says they want their porch light to always turn on at dusk, but never override it manually turning it off. How should this automation be designed?', 'أثناء التشغيل، يطلب العميل أن يضيء ضوء الشرفة دائمًا عند الغسق، لكن دون تجاوز إيقافه يدويًا. كيف يجب تصميم هذه الأتمتة؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Trigger the light at dusk, but add a condition that skips the trigger if manually turned off within the last few hours', 'تشغيل الضوء عند الغسق، مع إضافة شرط يتخطى التشغيل إذا تم إيقافه يدويًا خلال الساعات الأخيرة', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver' AND qq.question = 'During commissioning, a customer says they want their porch light to always turn on at dusk, but never override it manually turning it off. How should this automation be designed?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Trigger the light at dusk with no conditions at all', 'تشغيل الضوء عند الغسق بلا أي شروط', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver' AND qq.question = 'During commissioning, a customer says they want their porch light to always turn on at dusk, but never override it manually turning it off. How should this automation be designed?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'This requirement cannot be automated and must be done manually every day', 'لا يمكن أتمتة هذا المطلب ويجب فعله يدويًا كل يوم', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver' AND qq.question = 'During commissioning, a customer says they want their porch light to always turn on at dusk, but never override it manually turning it off. How should this automation be designed?';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'What''s the risk of not testing a garage door''s inching/pulse mode setting before handover?', 'ما مخاطر عدم اختبار إعداد وضع النبضة لباب الجراج قبل التسليم؟', 2 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The relay could hold the circuit closed continuously instead of pulsing, potentially damaging the door motor or leaving it in an unsafe state', 'قد يبقي الريليه الدائرة مغلقة باستمرار بدلًا من النبض، ما قد يضر بمحرك الباب أو يتركه في حالة غير آمنة', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver' AND qq.question = 'What''s the risk of not testing a garage door''s inching/pulse mode setting before handover?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'There is no risk; pulse mode is purely cosmetic', 'لا مخاطر؛ وضع النبضة تجميلي فقط', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver' AND qq.question = 'What''s the risk of not testing a garage door''s inching/pulse mode setting before handover?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'It only affects the app''s notification sounds', 'يؤثر فقط على أصوات إشعارات التطبيق', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'silver' AND qq.question = 'What''s the risk of not testing a garage door''s inching/pulse mode setting before handover?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'gold', title || ' — Gold Quiz', title_ar || ' — اختبار ذهبي', 85 FROM public.modules WHERE slug = 'sonoff-professional-installation';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A multi-zone commercial installation needs consistent behavior across 20 gateways managed by different technicians over time. What single practice most reduces configuration drift?', 'تركيب تجاري متعدد المناطق يحتاج سلوكًا متسقًا عبر 20 بوابة يديرها فنيون مختلفون بمرور الوقت. ما الممارسة الوحيدة الأكثر تقليلًا لانحراف الإعدادات؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'gold';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'A standardized, version-controlled configuration template applied to every gateway with documented deviations', 'قالب إعداد موحّد وخاضع للتحكم بالإصدارات يُطبّق على كل بوابة مع توثيق أي انحرافات', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'gold' AND qq.question = 'A multi-zone commercial installation needs consistent behavior across 20 gateways managed by different technicians over time. What single practice most reduces configuration drift?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Letting each technician configure gateways from memory without documentation', 'ترك كل فني يُعد البوابات من الذاكرة دون توثيق', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'gold' AND qq.question = 'A multi-zone commercial installation needs consistent behavior across 20 gateways managed by different technicians over time. What single practice most reduces configuration drift?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Using a different automation platform for each zone', 'استخدام منصة أتمتة مختلفة لكل منطقة', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-professional-installation' AND q.tier = 'gold' AND qq.question = 'A multi-zone commercial installation needs consistent behavior across 20 gateways managed by different technicians over time. What single practice most reduces configuration drift?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'silver', title || ' — Silver Quiz', title_ar || ' — اختبار فضي', 85 FROM public.modules WHERE slug = 'sonoff-smart-home-integration';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A Home Assistant automation and the eWeLink app both try to control the same device''s state simultaneously, causing flickering. What''s the likely fix?', 'أتمتة Home Assistant وتطبيق eWeLink يحاولان التحكم بحالة نفس الجهاز في آن واحد، ما يسبب وميضًا. ما الحل المحتمل؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Designate one platform as the source of truth for that device and disable competing automations on the other', 'تحديد منصة واحدة كمصدر الحقيقة لهذا الجهاز وتعطيل الأتمتة المتنافسة على الأخرى', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'silver' AND qq.question = 'A Home Assistant automation and the eWeLink app both try to control the same device''s state simultaneously, causing flickering. What''s the likely fix?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Increase the device''s Wi-Fi signal strength', 'زيادة قوة إشارة Wi-Fi للجهاز', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'silver' AND qq.question = 'A Home Assistant automation and the eWeLink app both try to control the same device''s state simultaneously, causing flickering. What''s the likely fix?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'This is normal behavior and doesn''t need fixing', 'هذا سلوك طبيعي ولا يحتاج إصلاحًا', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'silver' AND qq.question = 'A Home Assistant automation and the eWeLink app both try to control the same device''s state simultaneously, causing flickering. What''s the likely fix?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'gold', title || ' — Gold Quiz', title_ar || ' — اختبار ذهبي', 85 FROM public.modules WHERE slug = 'sonoff-smart-home-integration';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A customer wants Apple Home, Google Home, and Home Assistant to all control the same set of devices without conflicts. What architecture best supports this?', 'يريد العميل أن يتحكم Apple Home وGoogle Home وHome Assistant جميعًا بنفس مجموعة الأجهزة دون تعارض. ما البنية الأنسب لدعم ذلك؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'gold';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Matter-certified devices joined to a single fabric with multi-admin sharing across all three ecosystems', 'أجهزة معتمدة من Matter منضمة لنسيج واحد بمشاركة متعددة المشرفين عبر المنظومات الثلاث', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'gold' AND qq.question = 'A customer wants Apple Home, Google Home, and Home Assistant to all control the same set of devices without conflicts. What architecture best supports this?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Three separate sets of duplicate devices, one per ecosystem', 'ثلاث مجموعات منفصلة من أجهزة مكررة، واحدة لكل منظومة', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'gold' AND qq.question = 'A customer wants Apple Home, Google Home, and Home Assistant to all control the same set of devices without conflicts. What architecture best supports this?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'This configuration is technically impossible', 'هذا الإعداد مستحيل تقنيًا', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-smart-home-integration' AND q.tier = 'gold' AND qq.question = 'A customer wants Apple Home, Google Home, and Home Assistant to all control the same set of devices without conflicts. What architecture best supports this?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'silver', title || ' — Silver Quiz', title_ar || ' — اختبار فضي', 85 FROM public.modules WHERE slug = 'sonoff-device-specific-mastery';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A dimmer installed with an LED load flickers at low brightness even after setting a minimum floor. What should be checked next?', 'مفتاح تعتيم مركب بحمل LED يومض عند السطوع المنخفض حتى بعد ضبط حد أدنى. ما الذي يجب فحصه بعد ذلك؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Whether the dimming edge type (leading vs trailing) actually matches what the specific LED driver requires', 'ما إذا كان نوع حافة التعتيم (أمامية أم خلفية) يطابق فعليًا ما يتطلبه محول LED المحدد', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'silver' AND qq.question = 'A dimmer installed with an LED load flickers at low brightness even after setting a minimum floor. What should be checked next?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The color of the light fixture''s housing', 'لون هيكل تجهيزة الإضاءة', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'silver' AND qq.question = 'A dimmer installed with an LED load flickers at low brightness even after setting a minimum floor. What should be checked next?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The customer''s Wi-Fi router brand', 'العلامة التجارية لموجه Wi-Fi للعميل', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'silver' AND qq.question = 'A dimmer installed with an LED load flickers at low brightness even after setting a minimum floor. What should be checked next?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'gold', title || ' — Gold Quiz', title_ar || ' — اختبار ذهبي', 85 FROM public.modules WHERE slug = 'sonoff-device-specific-mastery';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'After flashing new firmware onto a Zigbee coordinator, all previously paired devices show as unreachable. What is the most likely cause and correct remediation?', 'بعد برمجة برنامج ثابت جديد على منسق Zigbee، تظهر كل الأجهزة المقترنة سابقًا كغير قابلة للوصول. ما السبب الأرجح والإصلاح الصحيح؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'gold';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The network''s PAN ID/encryption key changed with the reflash, so devices must be individually re-joined; restoring a backed-up network key can avoid this', 'تغيّر معرف الشبكة/مفتاح التشفير مع إعادة البرمجة، لذا يجب إعادة ضم الأجهزة فرديًا؛ استعادة مفتاح شبكة محفوظ مسبقًا يمكن أن يتجنب ذلك', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'gold' AND qq.question = 'After flashing new firmware onto a Zigbee coordinator, all previously paired devices show as unreachable. What is the most likely cause and correct remediation?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The devices are permanently broken and must be replaced', 'الأجهزة معطلة بشكل دائم ويجب استبدالها', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'gold' AND qq.question = 'After flashing new firmware onto a Zigbee coordinator, all previously paired devices show as unreachable. What is the most likely cause and correct remediation?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'This only happens with Wi-Fi devices, not Zigbee', 'يحدث هذا فقط مع أجهزة Wi-Fi لا Zigbee', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-device-specific-mastery' AND q.tier = 'gold' AND qq.question = 'After flashing new firmware onto a Zigbee coordinator, all previously paired devices show as unreachable. What is the most likely cause and correct remediation?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'silver', title || ' — Silver Quiz', title_ar || ' — اختبار فضي', 85 FROM public.modules WHERE slug = 'sonoff-network-troubleshooting';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A large property''s Zigbee network works fine near the gateway but battery sensors on the far side keep dropping. Routers are mains-powered devices spread throughout. What''s the likely diagnosis?', 'شبكة Zigbee في عقار كبير تعمل جيدًا قرب البوابة لكن حساسات البطارية في الجانب البعيد تنقطع باستمرار. الموجّهات أجهزة متصلة بالكهرباء منتشرة في كل مكان. ما التشخيص الأرجح؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Insufficient router density or hop count on the far side of the mesh, requiring an additional repeater there', 'كثافة موجّهات أو عدد قفزات غير كافٍ في الجانب البعيد من الشبكة، ما يتطلب معيد إشارة إضافي هناك', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'silver' AND qq.question = 'A large property''s Zigbee network works fine near the gateway but battery sensors on the far side keep dropping. Routers are mains-powered devices spread throughout. What''s the likely diagnosis?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The battery sensors need a firmware downgrade', 'الحساسات تحتاج خفض إصدار البرنامج الثابت', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'silver' AND qq.question = 'A large property''s Zigbee network works fine near the gateway but battery sensors on the far side keep dropping. Routers are mains-powered devices spread throughout. What''s the likely diagnosis?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Battery sensors cannot work more than 5 meters from a gateway under any circumstances', 'لا يمكن لحساسات البطارية العمل على بعد أكثر من 5 أمتار من البوابة تحت أي ظرف', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'silver' AND qq.question = 'A large property''s Zigbee network works fine near the gateway but battery sensors on the far side keep dropping. Routers are mains-powered devices spread throughout. What''s the likely diagnosis?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'gold', title || ' — Gold Quiz', title_ar || ' — اختبار ذهبي', 85 FROM public.modules WHERE slug = 'sonoff-network-troubleshooting';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'You''re designing a two-gateway deployment for a large estate where zones must share automations (e.g. a single ''goodnight'' scene across the whole property). What must be carefully coordinated between the gateways?', 'تصمم نشر بوابتين لعقار كبير حيث يجب أن تشترك المناطق في الأتمتة (مثل مشهد ''ليلة سعيدة'' واحد للعقار بأكمله). ما الذي يجب تنسيقه بعناية بين البوابتين؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'gold';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Channel assignment and PAN ID planning to run as a single extended network, or a higher-level automation platform that bridges both gateways'' scenes', 'تخصيص القناة وتخطيط معرف الشبكة للعمل كشبكة موسعة واحدة، أو منصة أتمتة أعلى تربط مشاهد البوابتين', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'gold' AND qq.question = 'You''re designing a two-gateway deployment for a large estate where zones must share automations (e.g. a single ''goodnight'' scene across the whole property). What must be carefully coordinated between the gateways?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Nothing — gateways automatically share automations by default', 'لا شيء — البوابات تشارك الأتمتة تلقائيًا افتراضيًا', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'gold' AND qq.question = 'You''re designing a two-gateway deployment for a large estate where zones must share automations (e.g. a single ''goodnight'' scene across the whole property). What must be carefully coordinated between the gateways?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'The gateways must be physically connected by an Ethernet cable to share any state', 'يجب توصيل البوابتين فعليًا بكابل إيثرنت لمشاركة أي حالة', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-network-troubleshooting' AND q.tier = 'gold' AND qq.question = 'You''re designing a two-gateway deployment for a large estate where zones must share automations (e.g. a single ''goodnight'' scene across the whole property). What must be carefully coordinated between the gateways?';

