-- Silver & gold tier quizzes for M16 (original writing).

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'silver', title || ' — Silver Quiz', title_ar || ' — اختبار فضي', 85 FROM public.modules WHERE slug = 'sonoff-mesh-security-hardening';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A customer''s smart home network mixes IoT devices with their work laptop on the same flat network. What''s the professional remediation during a service visit?', 'شبكة منزل العميل الذكي تخلط أجهزة إنترنت الأشياء مع كمبيوتر العمل المحمول على نفس الشبكة المسطحة. ما الإصلاح الاحترافي أثناء زيارة الصيانة؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Propose segmenting IoT traffic onto a separate VLAN or guest network while preserving the specific discovery protocols each device needs', 'اقتراح فصل حركة مرور إنترنت الأشياء على VLAN أو شبكة ضيوف منفصلة مع الحفاظ على بروتوكولات الاكتشاف التي يحتاجها كل جهاز', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver' AND qq.question = 'A customer''s smart home network mixes IoT devices with their work laptop on the same flat network. What''s the professional remediation during a service visit?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Tell the customer this is not a real security concern', 'إخبار العميل أن هذا ليس مصدر قلق أمني حقيقي', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver' AND qq.question = 'A customer''s smart home network mixes IoT devices with their work laptop on the same flat network. What''s the professional remediation during a service visit?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Disconnect the laptop from Wi-Fi permanently', 'فصل الكمبيوتر المحمول عن Wi-Fi بشكل دائم', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver' AND qq.question = 'A customer''s smart home network mixes IoT devices with their work laptop on the same flat network. What''s the professional remediation during a service visit?';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'A property manager wants former tenants'' smart-lock access revoked individually without resetting every device in the building. What access model supports this?', 'يريد مدير عقار إلغاء وصول المستأجرين السابقين للأقفال الذكية فرديًا دون إعادة ضبط كل جهاز في المبنى. أي نموذج وصول يدعم ذلك؟', 2 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Per-user shared access/roles rather than a single shared admin credential across all tenants', 'وصول/أدوار مشتركة لكل مستخدم بدلًا من بيانات اعتماد مسؤول واحدة مشتركة لجميع المستأجرين', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver' AND qq.question = 'A property manager wants former tenants'' smart-lock access revoked individually without resetting every device in the building. What access model supports this?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'A single master PIN shared by everyone in the building', 'رقم PIN رئيسي واحد يشاركه الجميع في المبنى', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver' AND qq.question = 'A property manager wants former tenants'' smart-lock access revoked individually without resetting every device in the building. What access model supports this?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Resetting all locks to factory defaults every time a tenant moves out', 'إعادة ضبط كل الأقفال للمصنع في كل مرة يغادر فيها مستأجر', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'silver' AND qq.question = 'A property manager wants former tenants'' smart-lock access revoked individually without resetting every device in the building. What access model supports this?';

INSERT INTO public.quizzes (module_id, tier, title, title_ar, pass_percent) SELECT id, 'gold', title || ' — Gold Quiz', title_ar || ' — اختبار ذهبي', 85 FROM public.modules WHERE slug = 'sonoff-mesh-security-hardening';
INSERT INTO public.quiz_questions (quiz_id, question, question_ar, position) SELECT q.id, 'You''re hardening a 40-device commercial deployment where different vendors'' firmware update cycles are unpredictable. What staged rollout strategy minimizes risk of a building-wide automation outage?', 'تُحصّن نشرًا تجاريًا لـ40 جهازًا حيث دورات تحديث البرامج الثابتة لموردين مختلفين غير متوقعة. ما استراتيجية الطرح المرحلي التي تقلل خطر انقطاع الأتمتة على مستوى المبنى؟', 1 FROM public.quizzes q JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'gold';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Update a small canary group first, monitor for automation regressions over a defined window, then roll out in batches while keeping a changelog', 'تحديث مجموعة تجريبية صغيرة أولًا، مراقبة أي تراجع في الأتمتة خلال فترة محددة، ثم الطرح على دفعات مع الاحتفاظ بسجل تغييرات', TRUE, 1 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'gold' AND qq.question = 'You''re hardening a 40-device commercial deployment where different vendors'' firmware update cycles are unpredictable. What staged rollout strategy minimizes risk of a building-wide automation outage?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Update all 40 devices simultaneously overnight with no monitoring', 'تحديث كل الأجهزة الأربعين دفعة واحدة ليلًا دون مراقبة', FALSE, 2 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'gold' AND qq.question = 'You''re hardening a 40-device commercial deployment where different vendors'' firmware update cycles are unpredictable. What staged rollout strategy minimizes risk of a building-wide automation outage?';
INSERT INTO public.quiz_options (question_id, option_text, option_text_ar, is_correct, position) SELECT qq.id, 'Disable all firmware updates permanently to avoid any risk', 'تعطيل كل تحديثات البرامج الثابتة بشكل دائم لتجنب أي مخاطرة', FALSE, 3 FROM public.quiz_questions qq JOIN public.quizzes q ON q.id = qq.quiz_id JOIN public.modules m ON m.id = q.module_id WHERE m.slug = 'sonoff-mesh-security-hardening' AND q.tier = 'gold' AND qq.question = 'You''re hardening a 40-device commercial deployment where different vendors'' firmware update cycles are unpredictable. What staged rollout strategy minimizes risk of a building-wide automation outage?';

