-- Module F07: Alpha Control Platform: Architecture, Protocols & Deployment

INSERT INTO public.modules (slug, code, track_id, title, title_ar, summary, summary_ar, external_url, position) VALUES ('finix-alpha-control-platform', 'F07', 'finix-technician-academy', 'Alpha Control Platform: Architecture, Protocols & Deployment', 'منصة Alpha Control: البنية والبروتوكولات والتركيب', 'Finix Systems'' Alpha Control stackable hub: core I/O architecture, multi-protocol connectivity, the three expansion modules and when to use each, and safety/environmental ratings for installation planning.', 'هب Alpha Control القابل للتكديس من Finix Systems: بنية الإدخال/الإخراج الأساسية، الاتصال متعدد البروتوكولات، وحدات التوسعة الثلاث ومتى تُستخدم كل منها، والتصنيفات البيئية والسلامة لتخطيط التركيب.', NULL, 24);
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'Alpha Control: What It Is and Why It Replaces a Wall of Controllers', 'Alpha Control: ما هو ولماذا يستبدل حائطًا كاملًا من وحدات التحكم', 'Most smart building installs end up with a patchwork of single-purpose controllers: one box for lighting, another for curtains, another for HVAC zoning, another for the sound system — each with its own wiring, its own app, and its own point of failure. Alpha Control is Finix Systems'' answer to that patchwork: a single stackable control hub built to run a whole floor, a whole production zone, or an entire small factory from one board.

At its core (the Alpha Core module), it exposes 16 AC input channels and 16 relay output channels — enough to sense 16 separate switches/sensors and independently switch 16 separate loads from one unit. That single board can cover lighting circuits, motorized curtains and shutters, smart plugs, sound routing, and security/access integration simultaneously, which is what lets it functionally replace a whole cabinet of dedicated single-purpose controllers in a typical installation.

**Why this matters to an installer, practically:** fewer boxes to mount means faster installs and a cleaner panel; fewer separate devices talking to the network means fewer possible points of failure and fewer firmware versions to keep track of; and because the whole unit runs one shared firmware across the core and all connected expansion boards, a single OTA update keeps everything in sync rather than updating five separate gadgets individually.

**Core specs to remember for quoting a job:** input voltage range 90–265V AC (works across most regional mains standards without a separate converter), relay rating 10A @ 250V AC per channel for standard loads, powered itself via a 12V DC / 3A barrel-jack supply, and standby power draw under 2W — low enough that leaving it always-on has negligible impact on the client''s electricity bill.', 'معظم تركيبات المباني الذكية تنتهي بمجموعة متفرقة من وحدات التحكم أحادية الغرض: صندوق للإضاءة، وآخر للستائر، وآخر لمناطق التكييف، وآخر لنظام الصوت — كل واحد بأسلاكه وتطبيقه ونقطة فشله الخاصة. Alpha Control هو حل شركة Finix Systems لهذا التشتت: هب تحكم واحد قابل للتكديس، مصمم لتشغيل طابق كامل، أو منطقة إنتاج كاملة، أو مصنع صغير بأكمله من لوحة واحدة.

في قلبه (وحدة Alpha Core)، يوفر 16 قناة إدخال متردد و16 قناة إخراج ريليه — تكفي لاستشعار 16 مفتاحًا/حساسًا منفصلًا والتحكم المستقل في 16 حملًا منفصلًا من وحدة واحدة. يمكن لتلك اللوحة الواحدة تغطية دوائر الإضاءة والستائر والمظلات الكهربائية والمقابس الذكية وتوجيه الصوت وتكامل الأمن والدخول في نفس الوقت، وهذا ما يجعلها تستبدل عمليًا خزانة كاملة من وحدات تحكم أحادية الغرض في تركيب نموذجي.

**لماذا يهم هذا الفني عمليًا:** صناديق أقل للتركيب يعني تركيبًا أسرع ولوحة أنظف؛ أجهزة منفصلة أقل تتواصل مع الشبكة يعني نقاط فشل محتملة أقل وإصدارات برنامج ثابت أقل يجب متابعتها؛ ولأن الوحدة بأكملها تعمل ببرنامج ثابت مشترك عبر الكور وكل لوحات التوسعة المتصلة، فإن تحديثًا واحدًا عبر الإنترنت (OTA) يُبقي كل شيء متزامنًا بدلًا من تحديث خمسة أجهزة منفصلة كل على حدة.

**مواصفات أساسية يجب تذكرها عند تسعير مشروع:** مدى جهد الإدخال 90-265 فولت متردد (يعمل عبر أغلب معايير الكهرباء الإقليمية دون محول منفصل)، تصنيف الريليه 10 أمبير عند 250 فولت متردد لكل قناة للأحمال القياسية، يُغذّى الجهاز نفسه عبر مزود 12 فولت مستمر / 3 أمبير بموصل دائري (barrel jack)، واستهلاك الطاقة في وضع الاستعداد أقل من 2 واط — منخفض بما يكفي لجعل تركه يعمل دائمًا بلا تأثير يُذكر على فاتورة كهرباء العميل.', 1 FROM public.modules WHERE slug = 'finix-alpha-control-platform';
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'Protocols & Connectivity: Why Alpha Control Isn''t Locked to One Platform', 'البروتوكولات والاتصال: لماذا لا يرتبط Alpha Control بمنصة واحدة', 'One of the most important things to communicate to a client evaluating Alpha Control is that it was designed protocol-agnostic from the start — it doesn''t force them into one ecosystem. It speaks Wi-Fi (2.4GHz) and Bluetooth Low Energy (BLE 4.2/5.0) for consumer-grade wireless connections, a wired Ethernet 10/100 RJ45 port for a rock-solid always-on connection, RS-485 with Modbus RTU master/slave support for industrial daisy-chaining and integration with existing industrial equipment, and I2C/SPI buses for connecting additional sensors directly at the board level. On top of that physical layer, it runs MQTT with TLS support for secure IoT messaging, plus HTTP, WebSocket, and Modbus TCP for software integration.

**What that protocol list translates to for platform compatibility:** the unit works natively with eWeLink (the same app ecosystem used across other Finix/SONOFF-family products, useful for clients who already have devices in that app), Home Assistant (for technically engaged clients wanting full local control and deep customization), and Finix Cloud (the manufacturer''s own dashboard, aimed at simpler management and centralized multi-unit oversight). Voice control reaches Alexa and Google Assistant indirectly, routed through the eWeLink integration rather than a direct proprietary skill.

**The practical installer takeaway:** because Alpha Control supports full local LAN/RS-485 control in addition to cloud OTA updates, it keeps working for on-site control even if the client''s internet connection drops — a meaningful reliability advantage over pure cloud-dependent devices, and a genuine selling point when quoting an industrial job where downtime has a real cost.

**Daisy-chaining and scale:** the unit is explicitly built to scale linearly — you can daisy-chain multiple Alpha Control units over RS-485 or Ethernet and group dozens of them under one shared Home Assistant or Finix Cloud dashboard for centralized management, which is the intended approach for anything larger than a single-zone install (e.g. a multi-floor building or a full production line).', 'أحد أهم الأمور التي يجب توضيحها لعميل يقيّم Alpha Control هو أنه صُمم منذ البداية ليكون محايدًا تجاه البروتوكولات — لا يُجبره على منصة واحدة. يتحدث الجهاز Wi-Fi (2.4 جيجاهرتز) وBluetooth Low Energy (BLE 4.2/5.0) للاتصالات اللاسلكية الاستهلاكية، منفذ إيثرنت سلكي 10/100 RJ45 لاتصال ثابت دائم التشغيل، RS-485 بدعم Modbus RTU (رئيسي/تابع) للتسلسل الصناعي والتكامل مع المعدات الصناعية القائمة، وناقلات I2C/SPI لتوصيل حساسات إضافية مباشرة على مستوى اللوحة. فوق هذه الطبقة الفيزيائية، يعمل الجهاز بـMQTT مع دعم TLS للمراسلة الآمنة لإنترنت الأشياء، بالإضافة إلى HTTP وWebSocket وModbus TCP للتكامل البرمجي.

**ماذا تعني قائمة البروتوكولات هذه من حيث توافق المنصات:** يعمل الجهاز أصلًا مع eWeLink (نفس منظومة التطبيق المستخدمة عبر منتجات Finix/SONOFF الأخرى، مفيد للعملاء الذين لديهم أجهزة بالفعل في ذلك التطبيق)، Home Assistant (للعملاء المهتمين تقنيًا الراغبين بتحكم محلي كامل وتخصيص عميق)، وFinix Cloud (لوحة تحكم الشركة المصنّعة الخاصة، موجهة للإدارة الأبسط والإشراف المركزي على عدة وحدات). يصل التحكم الصوتي إلى Alexa وGoogle Assistant بشكل غير مباشر، عبر تكامل eWeLink بدلًا من مهارة خاصة مباشرة.

**الخلاصة العملية للفني:** لأن Alpha Control يدعم تحكمًا محليًا كاملًا عبر الشبكة المحلية/RS-485 بالإضافة إلى تحديثات سحابية OTA، فإنه يستمر بالعمل للتحكم الموقعي حتى لو انقطع اتصال إنترنت العميل — ميزة موثوقية حقيقية مقارنة بالأجهزة المعتمدة كليًا على السحابة، ونقطة بيع حقيقية عند تسعير مشروع صناعي حيث للتوقف تكلفة حقيقية.

**التسلسل والتوسع:** الجهاز مبني صراحة للتوسع خطيًا — يمكنك تسلسل عدة وحدات Alpha Control عبر RS-485 أو الإيثرنت وتجميع عشرات منها تحت لوحة تحكم Home Assistant أو Finix Cloud واحدة مشتركة للإدارة المركزية، وهذا هو النهج المقصود لأي شيء أكبر من تركيب أحادي المنطقة (مثل مبنى متعدد الطوابق أو خط إنتاج كامل).', 2 FROM public.modules WHERE slug = 'finix-alpha-control-platform';
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'The Three Expansion Modules & When to Use Each', 'وحدات التوسعة الثلاث ومتى تُستخدم كل منها', 'Alpha Control''s stackable design is its most distinctive feature: the Alpha Core provides 3 expansion child-board slots, and each child board mounts directly onto the core via dedicated headers — no extra wiring runs required — with the core auto-detecting whatever''s plugged in and exposing those channels through every supported platform automatically. As an installer, choosing the right combination of child boards for a job is a core part of the design conversation with a client, not an afterthought.

**High-Current Module** — 4 channels at 50A each, 200A total capacity for this module (and the brochure cites 300A+ total system capacity when combined with the core''s own switching). Use case: loads far beyond what a standard 10A relay channel can safely handle — EV chargers, industrial motors, heat pumps, welding stations, large pumps and compressors. If a job spec sheet mentions any of those loads, this module isn''t optional, it''s mandatory — attempting to run them through the core''s standard 10A channels would be a serious safety violation.

**Sound System Module** — 8 channels of multi-zone audio routing with volume and source control. Use case: multi-room audio, ceiling speaker zoning, paging systems, and ambient background music for retail or hospitality venues. This is the module to spec whenever a project brief mentions whole-home audio or a commercial space wanting zoned background music.

**Interlock Module** — 4 channels of hardware interlock logic with fail-safe operation. Use case: anywhere two loads must never be energized simultaneously for safety reasons — door access control circuits, motor reversing pairs (forward/reverse can''t both engage at once), and any mutually exclusive load group. The key word here is *hardware* interlock — this protection is enforced at the circuit level, not just in software/firmware logic, so it keeps working correctly even during a firmware fault or network outage, which is exactly the guarantee safety-critical circuits need.

**Choosing modules for a real job — a worked scenario:** a small manufacturing floor needs 3 conveyor motors (each drawing well above 10A — High-Current Module), a paging system across 4 zones (Sound System Module), and a safety interlock so the conveyor and the loading-dock door motor can never run at the same time (Interlock Module). That''s exactly 3 modules — the maximum the core supports — covering all three functional needs from a single Alpha Core unit, with no additional standalone controllers required.', 'التصميم القابل للتكديس في Alpha Control هو أبرز ميزاته: يوفر Alpha Core 3 فتحات لوحات توسعة، وكل لوحة توسعة تُركَّب مباشرة على الكور عبر موصلات مخصصة — دون الحاجة لمسارات أسلاك إضافية — ويكتشف الكور تلقائيًا ما هو موصّل ويعرض تلك القنوات عبر كل منصة مدعومة تلقائيًا. كفني، اختيار التركيبة الصحيحة من لوحات التوسعة لمشروع ما جزء أساسي من محادثة التصميم مع العميل، لا فكرة لاحقة.

**وحدة التيار العالي (High-Current)** — 4 قنوات بـ50 أمبير لكل منها، سعة إجمالية 200 أمبير لهذه الوحدة (والكتيب يذكر سعة نظام إجمالية تفوق 300 أمبير عند الجمع مع قدرة التحويل الخاصة بالكور نفسه). حالة الاستخدام: أحمال تتجاوز بكثير ما يمكن لقناة ريليه قياسية 10 أمبير التعامل معها بأمان — شواحن السيارات الكهربائية، المحركات الصناعية، مضخات الحرارة، محطات اللحام، المضخات والضواغط الكبيرة. إذا ذكرت ورقة مواصفات المشروع أيًا من هذه الأحمال، فهذه الوحدة ليست اختيارية بل إلزامية — محاولة تشغيلها عبر قنوات الكور القياسية 10 أمبير ستكون مخالفة سلامة خطيرة.

**وحدة نظام الصوت (Sound System)** — 8 قنوات لتوجيه صوت متعدد المناطق مع تحكم بالصوت والمصدر. حالة الاستخدام: صوت متعدد الغرف، توزيع سماعات السقف، أنظمة النداء، والموسيقى الخلفية للمساحات التجارية أو الضيافة. هذه هي الوحدة التي تُحدد كلما ذكر ملخص المشروع صوتًا لكامل المنزل أو مساحة تجارية تريد موسيقى خلفية مقسّمة بمناطق.

**وحدة القفل التبادلي (Interlock)** — 4 قنوات بمنطق قفل تبادلي على مستوى العتاد (Hardware Interlock) مع تشغيل آمن عند الفشل. حالة الاستخدام: أي مكان يجب فيه ألا يعمل حملان في آن واحد لأسباب سلامة — دوائر التحكم بالدخول عبر الأبواب، أزواج عكس اتجاه المحرك (لا يمكن تفعيل الأمام والخلف معًا)، وأي مجموعة أحمال متبادلة الاستبعاد. الكلمة المفتاحية هنا هي القفل التبادلي *العتادي* — هذه الحماية مُطبّقة على مستوى الدائرة، لا فقط بمنطق برمجي/برنامج ثابت، لذا تستمر بالعمل بشكل صحيح حتى أثناء عطل في البرنامج الثابت أو انقطاع الشبكة، وهذا بالضبط الضمان الذي تحتاجه الدوائر الحرجة للسلامة.

**اختيار الوحدات لمشروع حقيقي — سيناريو محلول:** طابق تصنيع صغير يحتاج 3 محركات سيور ناقلة (كل منها يسحب أكثر من 10 أمبير بكثير — وحدة التيار العالي)، ونظام نداء عبر 4 مناطق (وحدة نظام الصوت)، وقفلًا تبادليًا للسلامة بحيث لا يعمل السير الناقل ومحرك باب منطقة التحميل في آن واحد أبدًا (وحدة القفل التبادلي). هذا بالضبط 3 وحدات — الحد الأقصى الذي يدعمه الكور — تغطي جميع الاحتياجات الوظيفية الثلاثة من وحدة Alpha Core واحدة، دون الحاجة لوحدات تحكم مستقلة إضافية.', 3 FROM public.modules WHERE slug = 'finix-alpha-control-platform';
INSERT INTO public.lessons (module_id, title, title_ar, content, content_ar, position) SELECT id, 'Safety, Environmental Ratings & Installation Considerations', 'السلامة والتصنيفات البيئية واعتبارات التركيب', 'Alpha Control is built for both residential and industrial environments, and its protection features reflect that dual purpose — an installer should be able to explain each of them to a client, not just recite the spec sheet.

**Built-in protection layers:**
- **Opto-isolated inputs** — the 16 AC input channels are electrically isolated from the control logic using optical coupling, meaning a voltage spike or fault on the sensed circuit can''t physically reach and damage the core''s processing electronics.
- **Fused outputs** — the relay outputs are individually protected by fuses, so a fault on one output channel blows that channel''s fuse rather than taking down the whole board or starting a fire risk.
- **Surge and TVS protection** — Transient Voltage Suppression components absorb brief high-voltage spikes (from lightning-induced surges or motor switching nearby) before they can reach sensitive components.
- **Hardware interlock (via the Interlock Module)** — as covered in the modules lesson, this safety layer is enforced in circuitry, not software, so it survives firmware crashes.

**Environmental and mechanical ratings to check against a job site before quoting:**
- Operating temperature range: **-10°C to +55°C** — check this against any planned outdoor, rooftop, or unconditioned mechanical-room installation location; an enclosure with some passive ventilation or shade may be needed at the upper end of that range in hot climates.
- Humidity tolerance: **10–90% non-condensing** — the "non-condensing" qualifier matters: this unit is not rated for locations where condensation regularly forms (e.g. unheated spaces with large temperature swings), and an enclosure with ventilation or a drip loop should be planned for borderline sites.
- Mounting: **DIN rail or panel mount** — standard electrical-panel mounting, meaning it drops into a typical distribution board or control cabinet without custom brackets.
- Certification: **CE and RoHS certified**, with FCC certification listed as pending at the time of this datasheet — worth double-checking current certification status before quoting a project in a market where FCC compliance is a hard requirement.

**A pre-installation checklist I''d give a technician for any Alpha Control job:** confirm the site''s mains voltage falls within 90–265V AC before committing to skip a separate voltage converter; confirm total connected relay load per channel doesn''t exceed 10A (route anything higher to the High-Current Module instead); confirm the mounting location''s ambient temperature and humidity fall within the rated ranges, especially for outdoor or mechanical-room placements; and confirm which of the 3 expansion slots will be populated up front, since retrofitting a module later means reopening the panel.', 'Alpha Control مصمم لبيئات سكنية وصناعية معًا، وميزات الحماية فيه تعكس هذا الغرض المزدوج — يجب على الفني أن يكون قادرًا على شرح كل منها للعميل، لا فقط تلاوة ورقة المواصفات.

**طبقات الحماية المدمجة:**
- **الإدخالات معزولة بصريًا (Opto-isolated)** — قنوات الإدخال المتردد الـ16 معزولة كهربائيًا عن منطق التحكم باستخدام الاقتران الضوئي، ما يعني أن ارتفاعًا مفاجئًا في الجهد أو عطلًا في الدائرة المستشعَرة لا يمكنه الوصول فعليًا لإتلاف إلكترونيات المعالجة في الكور.
- **إخراجات محمية بفيوز** — إخراجات الريليه محمية فرديًا بفيوزات، لذا فإن عطلًا في قناة إخراج واحدة يُفجّر فيوز تلك القناة فقط بدلًا من تعطيل اللوحة بأكملها أو خلق خطر حريق.
- **حماية من الطفرات وTVS** — مكونات قمع الجهد العابر (TVS) تمتص ارتفاعات الجهد القصيرة العالية (من طفرات ناتجة عن البرق أو تبديل محركات قريبة) قبل وصولها للمكونات الحساسة.
- **القفل التبادلي العتادي (عبر وحدة Interlock)** — كما ورد في درس الوحدات، طبقة السلامة هذه مُطبَّقة في الدائرة لا في البرنامج، لذا تنجو من أعطال البرنامج الثابت.

**تصنيفات بيئية وميكانيكية يجب التحقق منها بموقع العمل قبل التسعير:**
- مدى درجة حرارة التشغيل: **من -10 إلى +55 درجة مئوية** — تحقق من هذا مقابل أي موقع تركيب خارجي أو على السطح أو غرفة ميكانيكية غير مكيَّفة مخطط لها؛ قد يلزم صندوق بتهوية سلبية أو ظل عند الحد الأعلى من هذا المدى في المناخات الحارة.
- تحمل الرطوبة: **10-90٪ دون تكثف** — مؤهل "دون تكثف" مهم: هذا الجهاز غير مصنَّف لمواقع يتكوّن فيها تكثف بانتظام (مثل مساحات غير مدفأة بتقلبات حرارة كبيرة)، ويجب التخطيط لصندوق بتهوية أو حلقة تصريف للمواقع الحدّية.
- التركيب: **قضيب DIN أو تركيب لوحي** — تركيب قياسي للوحات الكهربائية، ما يعني أنه يُركَّب في لوحة توزيع أو خزانة تحكم نموذجية دون حاملات مخصصة.
- الشهادات: **معتمد CE وRoHS**، مع شهادة FCC مُدرجة كمعلّقة وقت إصدار هذه الورقة الفنية — يستحق التحقق المزدوج من حالة الاعتماد الحالية قبل تسعير مشروع في سوق تكون فيه مطابقة FCC شرطًا إلزاميًا.

**قائمة تحقق قبل التركيب أقدمها لأي فني لمشروع Alpha Control:** تأكد أن جهد الكهرباء الرئيسي بالموقع يقع ضمن 90-265 فولت متردد قبل الالتزام بتخطي محول جهد منفصل؛ تأكد أن إجمالي حمل الريليه المتصل لكل قناة لا يتجاوز 10 أمبير (وجّه أي حمل أعلى لوحدة التيار العالي بدلًا من ذلك)؛ تأكد أن درجة حرارة ورطوبة موقع التركيب المحيطة تقع ضمن المدى المصنَّف، خاصة للمواقع الخارجية أو غرف الميكانيكا؛ وتأكد أي من فتحات التوسعة الثلاث ستُملأ مسبقًا، لأن إضافة وحدة لاحقًا يعني إعادة فتح اللوحة.', 4 FROM public.modules WHERE slug = 'finix-alpha-control-platform';
